actions:
  - action_botfront_disambiguation
  - action_botfront_disambiguation_followup
  - action_botfront_fallback
  - action_botfront_mapping
  - action_unlikely_intent
  - utter_ask_age
  - utter_ask_location
  - utter_ask_name
  - utter_ask_team
  - utter_invalid_location
  - utter_invalid_team
  - utter_thanks
  - utter_valid_location
  - utter_valid_team
entities:
  - city
  - area
forms:
  test_form:
    required_slots:
        name:
          utter_on_new_valid_slot: false
          filling:
            - type: from_text
              intent: []
              not_intent: []
        age:
          utter_on_new_valid_slot: false
          filling:
            - type: from_text
              intent: []
              not_intent: []
        location:
          utter_on_new_valid_slot: true
          filling:
            - type: from_entity
              intent: inform.area
              not_intent: []
              entity: area
            - type: from_entity
              intent: inform.location
              not_intent: []
              entity: city
          validation:
            comparatum:
              - lappeenranta
              - taipalsaari
            operator: is_in
        team:
          utter_on_new_valid_slot: true
          filling:
            - type: from_text
              intent: team
              not_intent: []
          validation:
            comparatum:
              - saipa
              - tsv
            operator: is_in
    collect_in_botfront: null
    description: null
    graph_elements:
      edges:
        - condition: null
          id: e1-name
          source: '1'
          target: name
          type: condition
        - condition: null
          id: ename-age
          source: name
          target: age
          type: condition
        - condition: null
          id: eage-location
          source: age
          target: location
          type: condition
        - condition: null
          id: elocation-team
          source: location
          target: team
          type: condition
      nodes:
        - id: '1'
          position:
            x: 200
            'y': 200
          type: start
        - id: name
          position:
            x: 120
            'y': 350
          slotName: name
          type: slot
        - id: age
          position:
            x: 120
            'y': 500
          slotName: age
          type: slot
        - id: location
          position:
            x: 120
            'y': 660
          slotName: location
          type: slot
        - id: team
          position:
            x: 120
            'y': 800
          slotName: team
          type: slot
    groupName: examplestories
    name: test_form
intents:
  - greet
  - agree
  - inform.location
  - inform.area
  - team
responses:
  utter_ask_name:
  - text: "Anna nimi:"

  utter_ask_age:
  - text: "Anna ikä:"

  utter_ask_location:
  - text: "Mistä olet kotoisin?"
    metadata: null

  utter_ask_team:
  - text: "Mikä on suosikkijoukkueesi?"
    metadata: null

  utter_thanks:
  - text: "Kiitos!"

  utter_invalid_location:
  - text: "En tunne paikkakuntaa"

  utter_invalid_team:
  - text: "Tuo seura ei kuulosta hyvältä...."

  utter_valid_team:
  - text: "Tuo kuulostaa hyvältä"

  utter_valid_location:
  - text: "Paikkakunta tunnistettu"

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

slots:
  age:
    type: rasa.shared.core.slots.TextSlot
    initial_value: null
    auto_fill: true
    influence_conversation: false
  disambiguation_message:
    type: rasa.shared.core.slots.TextSlot
    initial_value: null
    auto_fill: true
    influence_conversation: false
  fallback_language:
    type: rasa.shared.core.slots.TextSlot
    initial_value: fi
    auto_fill: true
    influence_conversation: false
  name:
    type: rasa.shared.core.slots.TextSlot
    initial_value: null
    auto_fill: true
    influence_conversation: false
  location:
    type: rasa.shared.core.slots.TextSlot
    initial_value: null
    auto_fill: true
    influence_conversation: false
  team:
    type: rasa.shared.core.slots.TextSlot
    initial_value: null
    auto_fill: true
    influence_conversation: false

nlu:
- intent: greet
  examples: |
    - hei
    - moi
    - tere
    - moro

- intent: agree
  examples: |
    - ok
    - joo
    - kiitos
    - jeh

- intent: inform.location
  examples: |
    - asuin nuorena [lappeenrannassa]{"entity": "city", "value": "lappeenranta"}
    - juureni ovat [taipalsaarella]{"entity": "city", "value": "taipalsaari"}
    - lapsuudenkotini on [taipalsaarella]{"entity": "city", "value": "taipalsaari"}
    - olen kotoisin [lappeenrannasta]{"entity": "city", "value": "lappeenranta"}
    - vietin nuoruuteni [lappeenrannassa]{"entity": "city", "value": "lappeenranta"}
    - vietän kesät [taipalsaarella]{"entity": "city", "value": "taipalsaari"}

- intent: inform.area
  examples: |
    - murteeni on [karjalan]{"entity": "area", "value": "lappeenranta"}
    - murteeni on [karjalasta]{"entity": "area", "value": "lappeenranta"}
    - murteeni on [karjalaa]{"entity": "area", "value": "lappeenranta"}

- intent: team
  examples: |
    - tps
    - tsv
    - saipa

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 20
  - name: EntitySynonymMapper
language: fi

policies:
  - name: TEDPolicy
    epochs: 10
    max_history: 5
  - name: RulePolicy
  - name: MemoizationPolicy

stories:

- story: formstory
  steps:
  - intent: greet
  - action: test_form
  - active_loop: test_form
  - active_loop: null
  - action: utter_thanks
  - intent: agree
    entities: []

rules: []
